
import 'package:your_list_flutter_app/res/val/strings.dart';
import 'dart:async';
import 'package:chopper/chopper.dart';


part 'listService.chopper.dart';

@ChopperApi(baseUrl: "/lists")
/// ATTENTION: DO NOT MODIFY listService.chopper.dart it is auto
/// generated by flutter build runner
///
/// This service is responsible for obtaining and sending data regarding
/// lists users created
///
/// body variable must always contain UID of the user, getList must also contain
abstract class ListService extends ChopperService{

  @Get(path: "/readable_lists")
  Future<Response<List<String>>> getLists(@Body() Map<dynamic, dynamic> body);

  @Get()
  Future<Response> getList(@Body() Map<dynamic, dynamic> body);

  @Post()
  Future<Response> postList(@Body() Map<dynamic, dynamic> body);

  @Delete()
  Future<Response> deleteList(@Body() Map<dynamic, dynamic> body);

  static ListService create() {
    final client = ChopperClient(
      baseUrl: GlobalStrings.url,
      services: [
        _$ListService(),
      ],
      converter: JsonConverter(),
      interceptors: [HttpLoggingInterceptor()],
    );
    return _$ListService(client);
  }
}